export const FlavorProfile = [
    { label: "Dark Chocolate", key: "dark_chocolate" },
    { label: "Black Cherry", key: "black_cherry" },
    { label: "Citrus", key: "citrus" },
    { label: "Caramel", key: "caramel" },
    { label: "Cocoa", key: "cocoa" },
    { label: "Hazelnut", key: "hazelnut" },
    { label: "Molasses", key: "molasses" },
    { label: "Nutty", key: "nutty" },
    { label: "Smooth", key: "smooth" },
    { label: "Spicy", key: "spicy" },
    { label: "Earthy", key: "earthy" },
    { label: "Cinnamon", key: "cinnamon" },
    { label: "Clove", key: "clove" },
    { label: "Blueberry", key: "blueberry" },
    { label: "Blackcurrant", key: "blackcurrant" },
    { label: "Vanilla", key: "vanilla" },
    { label: "Floral", key: "floral" },
    { label: "Honey", key: "honey" },
    { label: "Smoke", key: "smoke" },
    { label: "Milk Chocolate", key: "milk_chocolate" },
    { label: "Tropical Fruit", key: "tropical_fruit" },
    { label: "Cardamom", key: "cardamom" },
    { label: "Fruit", key: "fruit" },
    { label: "Toffee", key: "toffee" },
    { label: "Coconut", key: "coconut" },
  ];
  